[package]
name = "app_dirs"
version = "1.2.1"
authors = ["Andy Barron <AndrewLBarron@gmail.com>"]

description = "Put your app's data in the right place on every platform"
documentation = "https://docs.rs/app_dirs"
repository = "https://github.com/AndyBarron/app-dirs-rs"
readme = "README.md"
keywords = ["application", "data", "storage", "location", "directory"]
license = "MIT"

[target.'cfg(all(unix, not(target_os="macos")))'.dependencies]
xdg = "^2.0.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["shlobj", "combaseapi"] }
